### ISSUE TITLE
stop recorder throws exception, I am starting the server with gstream

### ISSUE THREAD

**Issue by nagkumar** [ethand91/mediasoup3-record-demo#46]
w.r.t to https://github.com/ethand91/mediasoup3-record-demo codebase

at server on stoprecorder gives the following error with node14 lts verstion

socket::message [jsonMessage:{
  action: 'start-record',
  sessionId: 'bf620610-905e-11eb-93ec-09b099635e86'
}]
handleStartRecordRequest() [data:{
  action: 'start-record',
  sessionId: 'bf620610-905e-11eb-93ec-09b099635e86'
}]
publishProducerRtpStream()
createTransport() [type:plain. options:{
  listenIp: { ip: '0.0.0.0', announcedIp: undefined },
  rtcpMux: false,
  comedia: false
}]
(node:23840) UnhandledPromiseRejectionWarning: UnsupportedError: no compatible media codecs
    at Object.getConsumerRtpParameters (/home/nagkumar/nag/fork/mediasoup3-record-demo/server/node_modules/mediasoup/lib/ortc.js:690:15)
    at PlainTransport.consume (/home/nagkumar/nag/fork/mediasoup3-record-demo/server/node_modules/mediasoup/lib/Transport.js:290:36)
    at publishProducerRtpStream (/home/nagkumar/nag/fork/mediasoup3-record-demo/server/src/server.js:250:42)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async startRecord (/home/nagkumar/nag/fork/mediasoup3-record-demo/server/src/server.js:271:33)
(node:23840) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 14)
socket::message [jsonMessage:{
  action: 'stop-record',
  sessionId: 'bf620610-905e-11eb-93ec-09b099635e86'
}]
handleStopRecordRequest() [data:{
  action: 'stop-record',
  sessionId: 'bf620610-905e-11eb-93ec-09b099635e86'
}]
Failed to handle socket message [error:Error: Peer with id bf620610-905e-11eb-93ec-09b099635e86 is not recording
    at handleStopRecordRequest (/home/nagkumar/nag/fork/mediasoup3-record-demo/server/src/server.js:190:11)
    at handleJsonMessage (/home/nagkumar/nag/fork/mediasoup3-record-demo/server/src/server.js:99:20)
    at WebSocket.<anonymous> (/home/nagkumar/nag/fork/mediasoup3-record-demo/server/src/server.js:63:30)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/home/nagkumar/nag/fork/mediasoup3-record-demo/server/node_modules/ws/lib/websocket.js:825:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (/home/nagkumar/nag/fork/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:437:14)
    at Receiver.getData (/home/nagkumar/nag/fork/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:367:17)
    at Receiver.startLoop (/home/nagkumar/nag/fork/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/home/nagkumar/nag/fork/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:78:10) {
  [stack]: 'Error: Peer with id bf620610-905e-11eb-93ec-09b099635e86 is not recording\n' +
    '    at handleStopRecordRequest (/home/nagkumar/nag/fork/mediasoup3-record-demo/server/src/server.js:190:11)\n' +
    '    at handleJsonMessage (/home/nagkumar/nag/fork/mediasoup3-record-demo/server/src/server.js:99:20)\n' +
    '    at WebSocket.<anonymous> (/home/nagkumar/nag/fork/mediasoup3-record-demo/server/src/server.js:63:30)\n' +
    '    at WebSocket.emit (events.js:315:20)\n' +
    '    at Receiver.receiverOnMessage (/home/nagkumar/nag/fork/mediasoup3-record-demo/server/node_modules/ws/lib/websocket.js:825:20)\n' +
    '    at Receiver.emit (events.js:315:20)\n' +
    '    at Receiver.dataMessage (/home/nagkumar/nag/fork/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:437:14)\n' +
    '    at Receiver.getData (/home/nagkumar/nag/fork/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:367:17)\n' +
    '    at Receiver.startLoop (/home/nagkumar/nag/fork/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:143:22)\n' +
    '    at Receiver._write (/home/nagkumar/nag/fork/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:78:10)',
  [message]: 'Peer with id bf620610-905e-11eb-93ec-09b099635e86 is not recording'
}]
socket::message [jsonMessage:{
  action: 'start-record',
  sessionId: 'bf620610-905e-11eb-93ec-09b099635e86'
}]
handleStartRecordRequest() [data:{
  action: 'start-record',
  sessionId: 'bf620610-905e-11eb-93ec-09b099635e86'
}]
publishProducerRtpStream()
createTransport() [type:plain. options:{
  listenIp: { ip: '0.0.0.0', announcedIp: undefined },
  rtcpMux: false,
  comedia: false
}]

**Comment by nagkumar** [comment]
Can any provide the clues what the issue could be to fix?

`UnsupportedError: no compatible media codecs`

I do have all the encoders both 8 and 9

**Comment by ethand91** [comment]
```
at Object.getConsumerRtpParameters
```

It looks like the consumer does not support the media codecs of the Producer?
