### ISSUE TITLE
Unhandle Promise Rejection:

### ISSUE THREAD

**Issue by abhinavsy** [ethand91/mediasoup3-record-demo#79]
UnhandledPromiseRejectionWarning: TypeError: router.createPlainRtpTransport is not a function;
The video not recording the video because of this error.

**Comment by ansix** [comment]
change to router.createPlainTransport then it works

**Comment by abhinavsy** [comment]
> change to router.createPlainTransport then it works
This is the error  >>>
(node:45535) UnhandledPromiseRejectionWarning: TypeError: router.createPlainRtpTransport is not a function
    at module.exports.createTransport (/home/abhinav/Documents/mediasoup3-record-demo/server/src/mediasoup.js:47:27)
    at publishProducerRtpStream (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:213:30)
    at startRecord (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:271:39)
    at handleStartRecordRequest (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:178:3)
    at handleJsonMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:96:20)
    at WebSocket.<anonymous> (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:62:30)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/websocket.js:1098:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.dataMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:528:14)
(node:45535) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
socket::message [jsonMessage:{
  action: 'stop-record',
  sessionId: '08d7fb60-17c2-11ed-8e3b-a11df4457283'
}]
handleStopRecordRequest() [data:{
  action: 'stop-record',
  sessionId: '08d7fb60-17c2-11ed-8e3b-a11df4457283'
}]
Failed to handle socket message [error:Error: Peer with id 08d7fb60-17c2-11ed-8e3b-a11df4457283 is not recording
    at handleStopRecordRequest (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:190:11)
    at handleJsonMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:98:20)
    at WebSocket.<anonymous> (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:62:30)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/websocket.js:1098:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.dataMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:528:14)
    at Receiver.getData (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:148:22)
    at Receiver._write (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:83:10) {
  [stack]: 'Error: Peer with id 08d7fb60-17c2-11ed-8e3b-a11df4457283 is not recording\n' +
    '    at handleStopRecordRequest (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:190:11)\n' +
    '    at handleJsonMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:98:20)\n' +
    '    at WebSocket.<anonymous> (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:62:30)\n' +
    '    at WebSocket.emit (events.js:314:20)\n' +
    '    at Receiver.receiverOnMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/websocket.js:1098:20)\n' +
    '    at Receiver.emit (events.js:314:20)\n' +
    '    at Receiver.dataMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:528:14)\n' +
    '    at Receiver.getData (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:446:17)\n' +
    '    at Receiver.startLoop (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:148:22)\n' +
    '    at Receiver._write (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:83:10)',
  [message]: 'Peer with id 08d7fb60-17c2-11ed-8e3b-a11df4457283 is not recording'
}]
socket::message [jsonMessage:{
  action: 'start-record',
  sessionId: '08d7fb60-17c2-11ed-8e3b-a11df4457283'
}]
handleStartRecordRequest() [data:{
  action: 'start-record',
  sessionId: '08d7fb60-17c2-11ed-8e3b-a11df4457283'
}]
publishProducerRtpStream()
createTransport() [type:plain. options:{
  listenIp: { ip: '192.168.1.5', announcedIp: '192.168.1.5' },
  rtcpMux: true,
  comedia: false
}]
(node:45535) UnhandledPromiseRejectionWarning: TypeError: router.createPlainRtpTransport is not a function
    at module.exports.createTransport (/home/abhinav/Documents/mediasoup3-record-demo/server/src/mediasoup.js:47:27)
    at publishProducerRtpStream (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:213:30)
    at startRecord (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:271:39)
    at handleStartRecordRequest (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:178:3)
    at handleJsonMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:96:20)
    at WebSocket.<anonymous> (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:62:30)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/websocket.js:1098:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.dataMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:528:14)
(node:45535) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
socket::message [jsonMessage:{
  action: 'stop-record',
  sessionId: '08d7fb60-17c2-11ed-8e3b-a11df4457283'
}]
handleStopRecordRequest() [data:{
  action: 'stop-record',
  sessionId: '08d7fb60-17c2-11ed-8e3b-a11df4457283'
}]
Failed to handle socket message [error:Error: Peer with id 08d7fb60-17c2-11ed-8e3b-a11df4457283 is not recording
    at handleStopRecordRequest (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:190:11)
    at handleJsonMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:98:20)
    at WebSocket.<anonymous> (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:62:30)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/websocket.js:1098:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.dataMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:528:14)
    at Receiver.getData (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:148:22)
    at Receiver._write (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:83:10) {
  [stack]: 'Error: Peer with id 08d7fb60-17c2-11ed-8e3b-a11df4457283 is not recording\n' +
    '    at handleStopRecordRequest (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:190:11)\n' +
    '    at handleJsonMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:98:20)\n' +
    '    at WebSocket.<anonymous> (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:62:30)\n' +
    '    at WebSocket.emit (events.js:314:20)\n' +
    '    at Receiver.receiverOnMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/websocket.js:1098:20)\n' +
    '    at Receiver.emit (events.js:314:20)\n' +
    '    at Receiver.dataMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:528:14)\n' +
    '    at Receiver.getData (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:446:17)\n' +
    '    at Receiver.startLoop (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:148:22)\n' +
    '    at Receiver._write (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:83:10)',
  [message]: 'Peer with id 08d7fb60-17c2-11ed-8e3b-a11df4457283 is not recording'

**Comment by abhinavsy** [comment]
i have tried what you said,  but not working

(node:45535) UnhandledPromiseRejectionWarning: TypeError: router.createPlainRtpTransport is not a function
    at module.exports.createTransport (/home/abhinav/Documents/mediasoup3-record-demo/server/src/mediasoup.js:47:27)
    at publishProducerRtpStream (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:213:30)
    at startRecord (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:271:39)
    at handleStartRecordRequest (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:178:3)
    at handleJsonMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:96:20)
    at WebSocket.<anonymous> (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:62:30)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/websocket.js:1098:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.dataMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:528:14)
(node:45535) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
socket::message [jsonMessage:{
  action: 'stop-record',
  sessionId: '08d7fb60-17c2-11ed-8e3b-a11df4457283'
}]
handleStopRecordRequest() [data:{
  action: 'stop-record',
  sessionId: '08d7fb60-17c2-11ed-8e3b-a11df4457283'
}]
Failed to handle socket message [error:Error: Peer with id 08d7fb60-17c2-11ed-8e3b-a11df4457283 is not recording
    at handleStopRecordRequest (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:190:11)
    at handleJsonMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:98:20)
    at WebSocket.<anonymous> (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:62:30)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/websocket.js:1098:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.dataMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:528:14)
    at Receiver.getData (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:148:22)
    at Receiver._write (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:83:10) {
  [stack]: 'Error: Peer with id 08d7fb60-17c2-11ed-8e3b-a11df4457283 is not recording\n' +
    '    at handleStopRecordRequest (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:190:11)\n' +
    '    at handleJsonMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:98:20)\n' +
    '    at WebSocket.<anonymous> (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:62:30)\n' +
    '    at WebSocket.emit (events.js:314:20)\n' +
    '    at Receiver.receiverOnMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/websocket.js:1098:20)\n' +
    '    at Receiver.emit (events.js:314:20)\n' +
    '    at Receiver.dataMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:528:14)\n' +
    '    at Receiver.getData (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:446:17)\n' +
    '    at Receiver.startLoop (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:148:22)\n' +
    '    at Receiver._write (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:83:10)',
  [message]: 'Peer with id 08d7fb60-17c2-11ed-8e3b-a11df4457283 is not recording'
}]
socket::message [jsonMessage:{
  action: 'start-record',
  sessionId: '08d7fb60-17c2-11ed-8e3b-a11df4457283'
}]
handleStartRecordRequest() [data:{
  action: 'start-record',
  sessionId: '08d7fb60-17c2-11ed-8e3b-a11df4457283'
}]
publishProducerRtpStream()
createTransport() [type:plain. options:{
  listenIp: { ip: '0.0.0.0, announcedIp: '0.0.0.0' },
  rtcpMux: true,
  comedia: false
}]
(node:45535) UnhandledPromiseRejectionWarning: TypeError: router.createPlainRtpTransport is not a function
    at module.exports.createTransport (/home/abhinav/Documents/mediasoup3-record-demo/server/src/mediasoup.js:47:27)
    at publishProducerRtpStream (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:213:30)
    at startRecord (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:271:39)
    at handleStartRecordRequest (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:178:3)
    at handleJsonMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:96:20)
    at WebSocket.<anonymous> (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:62:30)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/websocket.js:1098:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.dataMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:528:14)
(node:45535) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
socket::message [jsonMessage:{
  action: 'stop-record',
  sessionId: '08d7fb60-17c2-11ed-8e3b-a11df4457283'
}]
handleStopRecordRequest() [data:{
  action: 'stop-record',
  sessionId: '08d7fb60-17c2-11ed-8e3b-a11df4457283'
}]
Failed to handle socket message [error:Error: Peer with id 08d7fb60-17c2-11ed-8e3b-a11df4457283 is not recording
    at handleStopRecordRequest (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:190:11)
    at handleJsonMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:98:20)
    at WebSocket.<anonymous> (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:62:30)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/websocket.js:1098:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.dataMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:528:14)
    at Receiver.getData (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:148:22)
    at Receiver._write (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:83:10) {
  [stack]: 'Error: Peer with id 08d7fb60-17c2-11ed-8e3b-a11df4457283 is not recording\n' +
    '    at handleStopRecordRequest (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:190:11)\n' +
    '    at handleJsonMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:98:20)\n' +
    '    at WebSocket.<anonymous> (/home/abhinav/Documents/mediasoup3-record-demo/server/src/server.js:62:30)\n' +
    '    at WebSocket.emit (events.js:314:20)\n' +
    '    at Receiver.receiverOnMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/websocket.js:1098:20)\n' +
    '    at Receiver.emit (events.js:314:20)\n' +
    '    at Receiver.dataMessage (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:528:14)\n' +
    '    at Receiver.getData (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:446:17)\n' +
    '    at Receiver.startLoop (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:148:22)\n' +
    '    at Receiver._write (/home/abhinav/Documents/mediasoup3-record-demo/server/node_modules/ws/lib/receiver.js:83:10)',
  [message]: 'Peer with id 08d7fb60-17c2-11ed-8e3b-a11df4457283 is not recording'

**Comment by ethand91** [comment]
If mediasoup is newer than version 3.5.0, you may need to use this:
https://mediasoup.org/documentation/v3/mediasoup/api/#PlainTransport
